//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointIT.WinUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppointIT.WinUI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string CurrencyKM {
            get {
                return ResourceManager.GetString("CurrencyKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string DurationMin {
            get {
                return ResourceManager.GetString("DurationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum isteka ne može biti mlađi od datuma početka..
        /// </summary>
        internal static string EndDateEarierThenStartDate {
            get {
                return ResourceManager.GetString("EndDateEarierThenStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške..
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje Lat ili Lng nije ispravnog formata..
        /// </summary>
        internal static string ErrorMsgInvalidLatAndLng {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidLatAndLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešan email ili lozinka. .
        /// </summary>
        internal static string ErrorMsgUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorMsgUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uređivanje novosti.
        /// </summary>
        internal static string NewsEdit {
            get {
                return ResourceManager.GetString("NewsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće kreirati termin na datum koji je prošao..
        /// </summary>
        internal static string PastDateErrorMessage {
            get {
                return ResourceManager.GetString("PastDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće kreirati kupon na datum koji je prošao..
        /// </summary>
        internal static string PastDateErrorMessageCoupon {
            get {
                return ResourceManager.GetString("PastDateErrorMessageCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polje treba sadržavati brojčanu vrijednost..
        /// </summary>
        internal static string RequiredNumberValue {
            get {
                return ResourceManager.GetString("RequiredNumberValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme početka i kraja termina nije podudarno sa trajanjem usluge..
        /// </summary>
        internal static string StartAndEndDurationErrorMessage {
            get {
                return ResourceManager.GetString("StartAndEndDurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodavanje..
        /// </summary>
        internal static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno brisanje.
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješna izmjena..
        /// </summary>
        internal static string SuccessEdit {
            get {
                return ResourceManager.GetString("SuccessEdit", resourceCulture);
            }
        }
    }
}
