version: '3'
services:
#mssql docker
  appointit-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 80:80
    expose:
        - 80
    networks:
      - AppointITnet

  appointit-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=appointit-sql,1433;Database=AppointIT;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:5001
    networks:
      - AppointITnet     
    links:
      - appointit-sql
    depends_on:
      - appointit-sql
      
networks:
  AppointITnet:
    driver: bridge 